version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-latest
    steps:
      - checkout
      - run: sgrep-lint -validate .
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
