version: 2.1
jobs:
  test:
    docker:
      - image: returntocorp/sgrep-build:2.3
    steps:
      - checkout
      - run: make test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
