version: 2.1
jobs:
  test:
    docker:
      - image: returntocorp/sgrep
    steps:
      - run: apk add make
      - checkout
      - run: make test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
