rules:
- id: avoid_app_run_with_bad_host
  patterns:
  - pattern-either:
    - pattern: app.run(..., host="0.0.0.0", ...)
    - pattern: app.run(..., "0.0.0.0", ...)
  message: Running flask app with host 0.0.0.0 could expose the server publicly.
  languages:
  - python
  severity: WARNING
  metadata:
    cwe: 'CWE-668: Exposure of Resource to Wrong Sphere'
    owasp: 'A6: Security Misconfiguration'
