name: semgrep-develop

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  test-develop:
    runs-on: ubuntu-latest
    name: test-develop
    steps:
    - uses: actions/checkout@v2
    - name: test
      id: test
      uses: returntocorp/semgrep-rules-test-action-develop@master
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: tests
        path: ${{ steps.test.outputs.output_dir }}
    - uses: actions/upload-artifact@v2
      with:
        name: semgrep_runs
        path: semgrep_runs_output.tar.gz
        if-no-files-found: error
    - uses: zdurham/s3-upload-github-action@master
      env:
        FILE: semgrep-runs_output.tar.gz
        AWS_REGION: us-east-1
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        S3_KEY: ${{ secrets.S3_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
